name: Python repitup application

on: push

permissions:
  contents: read

jobs:
  build:
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.9"
      - name: Set environment variables
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "HOST=127.0.0.1" >> $GITHUB_ENV
          echo "TEST_DB=${{ secrets.TEST_DB }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done
      - name: Initialize and migrate database
        run: |
          aerich init -t database.TORTOISE_ORM_TEST || echo "Aerich already initialized, continuing..."
          aerich init-db || echo "Database already initialized, continuing..."
      - name: Test with pytest
        run: |
          pytest test_project.py
