# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python repitup application

on: push

permissions:
  contents: read

jobs:
  build:
    services:
      db:
        image: postgres
        env:
          POSTGRES_USERNAME: ${{ secrets.USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.9"
      - name: Set enviroment variables
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          TEST_DB: ${{ secrets.TEST_DB }}
        run: echo "Enviroment Varibles sset"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          aerich init -t database.TORTOISE_ORM_TEST
          aerich init-db || echo "Database already initialized, continuing..."
          pytest test_project.py
