name: Python repitup application

on: push

permissions:
  contents: read

jobs:
  build:
    services:
      db:
        image: postgres
        env:
          POSTGRES_USERNAME: ${{ secrets.USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.9"
      - name: Set environment variables
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          TEST_DB: ${{ secrets.TEST_DB }}
        run: echo "Environment variables set"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio anyio
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done
      - name: Test with pytest
        run: |
          pytest test_project.py